name: Windows-MSYS2

on:
  pull_request:
    branches: [main, release-*]
  push:
    branches: [main, test*, release-*]

jobs:
  build:
    name: MSYS2 Tanzu CLI Core E2E Tests on Windows
    runs-on: windows-latest

    steps:
      - name: Set and Echo GOPATH and GOBIN
        run: |
          pwd
          docker run --isolation=hyperv --rm -d --name central stefanscherer/registry-windows:latest
        shell: pwsh

