name: Windows-MSYS2

on:
  pull_request:
    branches: [main, release-*]
  push:
    branches: [main, test*, release-*]

jobs:
  build:
    name: MSYS2 Tanzu CLI Core E2E Tests on Windows
    runs-on: windows-latest

    steps:
      - name: Set and Echo GOPATH and GOBIN
        run: |
          pwd
          docker run --isolation=hyperv --rm -d -p 9876:443 --name central -e REGISTRY_HTTP_ADDR=0.0.0.0:443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/localhost.crt -e REGISTRY_HTTP_TLS_KEY=/certs/localhost.key -v "D:\a\tanzu-cli\tanzu-cli;c:\registry" stefanscherer/registry-windows:latest
        shell: pwsh

